services:
  backend:
    build: .
    container_name: backend
    restart: "unless-stopped"
    volumes:
      - "./app/sqlite.db:/app/sqlite.db"
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend.entrypoints=https
      - traefik.http.routers.backend.rule=Host(`vv.shamps.dev`) && (PathPrefix(`/api`) || PathPrefix(`/docs`) || PathPrefix(`/openapi.json`))
      - traefik.http.routers.backend.tls.certresolver=letsEncrypt
      - traefik.http.services.backend.loadbalancer.server.port=8000
    networks:
      - traefik


networks:
  traefik:
    name: traefik
    external: true